Add support for the LFLOOR and LCEIL builtins, which represent a call to floor (resp. ceil) with the result cast to an integer type.  Before, programs that performed such a cast would fail to link due to an undefined reference to __builtin_lfloor or __builtin_lceil, or a variant of these. Use some of the added infrastructure to simplify the handling of ABS_EXPR (in the floating point case) while there.
llvm-svn: 118499